### ISSUE TITLE
Example of full usage

### ISSUE THREAD

**Issue by euforic** [playlyfe/go-graphql#10]
Could you share and example using the pkg with `net/http`

**Comment by euforic** [comment]
I ported the [graphql-go/handler](https://github.com/graphql-go/handler) over to your pkg https://github.com/bh5-go/gqlhandler.

Everything seems to work except with graphiql I get a panic when doing the introspection query for the docs.

### panic output
```
panic: Unknown Type 
goroutine 20 [running]:
runtime/debug.Stack(0xc42004f298, 0x25ac60, 0xc4200da550)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/playlyfe/go-graphql.(*Executor).resolveGroupedFields.func1.1(0xc4200da4c0, 0xc4201341e0, 0xc4200da4b0)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/executor.go:1011 +0x6e
panic(0x25ac60, 0xc4200da550)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/playlyfe/go-graphql.(*Executor).introspectType(0xc420108000, 0xc420108140, 0x25ac60, 0xc4200da510, 0xc4200da510)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/schema.go:162 +0xadb
github.com/playlyfe/go-graphql.NewSchema.func1(0xc420108140, 0xc420108140, 0xc4200d9170, 0x0, 0x0)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/schema.go:276 +0x13d
github.com/playlyfe/go-graphql.(*Executor).resolveFieldOnObject(0xc420108000, 0xc42012cb40, 0xc4200f2060, 0x26f340, 0xc42012cb70, 0x24db00, 0xc420100d60, 0xc4200e22a0, 0xc42002de20, 0xda864, ...)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/executor.go:1357 +0xfd4
github.com/playlyfe/go-graphql.(*Executor).getFieldEntry(0xc420108000, 0xc42012cb40, 0xc4200f2060, 0x26f340, 0xc42012cb70, 0xc420122622, 0x8, 0xc4200dc058, 0x1, 0x1, ...)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/executor.go:1067 +0xef
github.com/playlyfe/go-graphql.(*Executor).resolveGroupedFields.func1(0xc4200da4c0, 0xc4201341e0, 0xc4200da4b0, 0xc420108000, 0xc42012cb40, 0xc4200f2060, 0x26f340, 0xc42012cb70, 0xc4201341c0, 0xc4200da338, ...)
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/executor.go:1018 +0x102
created by github.com/playlyfe/go-graphql.(*Executor).resolveGroupedFields
	/Users/euforic/gocode/src/github.com/playlyfe/go-graphql/executor.go:1032 +0x47f
```

**Comment by euforic** [comment]
closing since I was able to get things working. I have included a example usage below.

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/bh5-go/gqlhandler"
	graphql "github.com/playlyfe/go-graphql"
)

// Schema Definition
const schema = `
interface Pet {
    name: String
}

type Dog implements Pet {
    name: String
    woofs: Boolean
}

type Cat implements Pet {
    name: String
    meows: Boolean
}

type QueryRoot {
	pets(a: String): [Pet]
}
`

var gql *graphql.Executor

func init() {
	var err error
	resolvers := map[string]interface{}{
		"QueryRoot/pets": petsQuery,
	}

	gql, err = graphql.NewGraphQL(&graphql.GraphQLParams{
		SchemaDefinition: schema,
		QueryRoot:        "QueryRoot",
		Resolvers:        resolvers,
		ResolveType:      resolveType,
	})
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	h := gqlhandler.New(gql)
	http.Handle("/graphql", h)
	fmt.Println("Now server is running on port 8080")
	http.ListenAndServe(":8080", nil)

}

// Type Resolver
func resolveType(value interface{}) string {
	if object, ok := value.(map[string]interface{}); ok {
		return object["__typename"].(string)
	}
	return ""
}

// PetQuery Resolver
func petsQuery(params *graphql.ResolveParams) (interface{}, error) {
	return []map[string]interface{}{
		{
			"__typename": "Dog",
			"name":       "Odie",
			"woofs":      true,
		},
		{
			"__typename": "Cat",
			"name":       "Garfield",
			"meows":      false,
		},
	}, nil
}
```
